### ISSUE TITLE
Ft897 on serial port

### ISSUE THREAD

**Issue by frspin** [LA5NTA/wl2k-go#13]
Ubuntu 14.04 - 64 bit
Ft897 connected to /dev/ttyUSB0 at 38400
Command:

wl2k connect winmor:DB0ZAV@7048500

give:

2015/10/07 21:14:24 ft897 ready. Dial frequency is 17.870.00 MHz.
2015/10/07 21:14:24 QSY winmor: 7048500
2015/10/07 21:14:24 Unable to QSY: Hamlib rig  not loaded.

Initial rig frequency is correct so I suppose that rig config is OK.
Winmor TNC is running under Wine.
It is my fault or a bug?

Regards
Franco Spinelli
IW2DHW

**Comment by martinhpedersen** [comment]
Hi Franco,

could you please try @7048.500 instead of @7048500?

The unit for frequency is KHz, and that should probably be better
documentet I guess.

If this resolves the issue for you, then that misleading error message
definitely is a bug, hehe.

Thanks for reporting the issue!

-- 
73 de LA5NTA

**Comment by martinhpedersen** [comment]
One more thing:

How does your config look? Have you defined which rig winmor should use?

**Comment by frspin** [comment]
Il 07/10/2015 22:02, Martin Hebnes Pedersen ha scritto:
> Hi Franco,
> 
> could you please try @7048.500 instead of @7048500?
> 
> The unit for frequency is KHz, and that should probably be better
> documentet I guess.
> 
> If this resolves the issue for you, then that misleading error message
> definitely is a bug, hehe.
> 

Same issue.

Command:

wl2k connect winmor:DB0ZAV@7048.500

give

2015/10/07 22:05:03 ft897 ready. Dial frequency is 17.870.00 MHz.
2015/10/07 22:05:03 QSY winmor: 7048.500
2015/10/07 22:05:03 Unable to QSY: Hamlib rig  not loaded.

And this is my config.json file:

{
  "mycall": "IW2DHW",
  "secure_login_password": "",
  "auxiliary_addresses": [],
  "locator": "JN45OP",
  "motd": [
    "Open source WL2K client - github.com/LA5NTA/wl2k-go"
  ],
  "connect_aliases": {},
  "listen": null,
  "hamlib_rigs": {
     "ft897": {
         "network": "serial",
         "address": "/dev/ttyUSB0?model=123&baudrate=38400"
         }
  },
  "ax25": {
    "port": "",
    "beacon": {
      "every": 3600,
      "message": "Winlink P2P",
      "destination": "IDENT"
    }
  },
  "serial-tnc": {
    "path": "/dev/ttyUSB0",
    "baudrate": 9600,
    "type": "Kenwood"
  },
  "winmor": {
    "addr": "localhost:8500",
    "inbound_bandwidth": 1600,
    "rig": "",
    "ptt_ctrl": false
  },
  "telnet": {
    "listen_addr": ":8774",
    "password": ""
  },
  "schedule": null
}

But, if getting frequency is working, dialog with rig is correct.

Regards

Franco Spinelli
IW2DHW

**Comment by martinhpedersen** [comment]
Yes, the hamlib config looks good and the rig communication seems to work properly. To put it short: the application is loading the rig, but does not know that the rig is associated with winmor :) 

If you add "rig":"ft897" under the "winmor" section in your config I believe things should start working properly :)

Example:
```
 "winmor": {
    "addr": "localhost:8500",
    "inbound_bandwidth": 1600,
    "rig": "ft897",
    "ptt_ctrl": false
  },
```

**Comment by martinhpedersen** [comment]
Please let me know if this resolves your problem. I think the error message you got could be more descriptive of the actual problem, so I will try to fix that.

**Comment by frspin** [comment]
Il 07/10/2015 22:29, Martin Hebnes Pedersen ha scritto:
> Please let me know if this resolves your problem. I think the error
> message you got could be more descriptive of the actual problem, so I
> will try to fix that.
> 

Yes, this solve the problem.
Obviously I have tested this without a real audio connection from TCN to
rig.

This is on my console:

2015/10/07 22:39:03 ft897 ready. Dial frequency is 17.870.00 MHz.
2015/10/07 22:39:03 QSY winmor: 7048.500
2015/10/07 22:39:05 Connecting to winmor:DB0ZAV@7048.500...
2015/10/07 22:39:07 WINMOR TNC v1.5.8.0 initialized
2015/10/07 22:39:45 Unable to establish connection to remote: Connect
timeout
2015/10/07 22:39:46 QSX winmor: 17870.000

There is a documentation of this config file?
Is "ptt_ctrl" related to ptt control with CAT command?

Regards and tank you

Franco Spinelli
IW2DHW

**Comment by martinhpedersen** [comment]
Glad to hear that it resolved the issue. The log output looks like everything is working as expected.

Yes, there is some documentation related to the config file at https://godoc.org/github.com/LA5NTA/wl2k-go/cmd/wl2k/cfg. It is no proper documentation describing the overall json structure, but all fields and the meaning is described there.

See also https://github.com/LA5NTA/wl2k-go/wiki/Building-from-source#example-configuration-file

My main focus regarding documentation has been on the related libraries for now.

Regarding ptt_ctrl: Yes, set it to true and you have enabled CAT ptt control for winmor :)

**Comment by frspin** [comment]
Il 07/10/2015 22:56, Martin Hebnes Pedersen ha scritto:
> Glad to hear that it resolved the issue. The log output looks like
> everything is working as expected.
> 
> Yes, there is some documentation related to the config file at
> https://godoc.org/github.com/LA5NTA/wl2k-go/cmd/wl2k/cfg. It is no
> proper documentation describing the overall json structure, but all
> fields and the meaning is described there.
> 
> See also
> https://github.com/LA5NTA/wl2k-go/wiki/Building-from-source#example-configuration-file
> 
> My main focus regarding documentation has been on the related libraries
> for now.
> 
> Regarding ptt_ctrl: Yes, set it to true and you have enabled CAT ptt
> control for winmor :)
> 

OK
I will read this documentation and do some more test using a "real"
audio connection to my rig.

There is some usage of rmslist.json file?

Regards

Franco Spinelli
IW2DHW

**Comment by martinhpedersen** [comment]
Sounds great, be sure to send me an email over winlink with your progress :)

> There is some usage of rmslist.json file?

I'm not sure I understand what your question is, but the rmslist.json file is the file backing the command "rmslist". If you run `wl2k rmslist help` you'll get some usage help. It basically lists all RMS and lets you search by callsign to look up frequencies etc. In the future I hope we are able to add path quality and related info under this command :)

**Comment by frspin** [comment]
2015-10-07 23:14 GMT+02:00 Martin Hebnes Pedersen <notifications@github.com>
:

> Sounds great, be sure to send me an email over winlink with your progress
> :)
>

Yes, I will do it


> There is some usage of rmslist.json file?
>
> I'm not sure I understand what your question is, but the rmslist.json file
> is the file backing the command "rmslist". If you run wl2k rmslist help
> you'll get some usage help. It basically lists all RMS and lets you search
> by callsign to look up frequencies etc. In the future I hope we are able to
> add path quality and related info under this command :)
>
>
I have seen rmslist command. I suppose this is updatet by Internet.
I need to study all options for selecting only station with a specific mode
(i.e. winmor) and a specific range (locator based)

Regards

Franco Spinelli
IW2DHW
