### ISSUE TITLE
cmd/wl2k: Display distance to node in rmslist

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/wl2k-go#14]
Need a way to calculate distance between maidenhead locators for this.

**Comment by frspin** [comment]
If needed, I have done some work in Python3/Qt5 for calculating a table of Winmor station starting from rmslist. I calculate distance, bearing, path reliability and path quality (using itshfbc)

Regards
Franco Spinelli
IW2DHW

**Comment by martinhpedersen** [comment]
Hi again Franco,

this sounds interesting. It would be nice to see the code so I have some reference. Are the source code available online?

**Comment by frspin** [comment]
Il 01/11/2015 13:51, Martin Hebnes Pedersen ha scritto:
> Hi again Franco,
> 
> this sounds interesting. It would be nice to see the code so I have some
> reference. Are the source code available online?

No source online. Is attached to this mail.

A "main" (tablemodel.py) and a library (voacap).
Python3 and PyQt required for GUI.

GUI is copied from example in Internet.
Function for distance and bearing are converted form a C library
Voacap id adapted from pythonprop

Use it as needed. No copyright problem at all for me!

Regards

Franco Spinelli
IW2DHW

**Comment by martinhpedersen** [comment]
Sorry, but attachments does not work on github issues. I have sent my regular email address to you via winlink. If you could send the source code to that address, I would really appreciate it.

This sounds very good, thank you for sharing it with the project :)

**Comment by martinhpedersen** [comment]
This issue was moved to la5nta/pat#4
