### ISSUE TITLE
transport: Add a pure Go AX.25 implementation

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/wl2k-go#36]
It would be nice to be able to support AX.25 platform-independent.

This will probably be a project on it's own.

**Comment by martinhpedersen** [comment]
I stumbled across a promising node project that implements the full stack:
https://github.com/echicken/node-ax25

It could be a nice starting-point. Maybe we could port it to Go?

**Comment by LightAxe** [comment]
How hard would it be to just bundle node-ax25 and call it directly?

**Comment by martinhpedersen** [comment]
@LightAxe - I don't know if anyone have attempted to call node/javascript code from Go, but it would require bundling a js/node engine with the library and a rather complicated wrapper I presume. I think our best bet is to port an existing and well tested implementation to Go.

I've opened a new issue for future discussions on this topic: Issue #56.

**Comment by cminyard** [comment]
I have just finished implementing an AX25 library in C.  It's part of the gensio library at https://github.com/cminyard/gensio and it's portable to Windows, MacOS, and Linux.  It has C++ and Python bindings at the moment.  I assume Go wouldn't be very hard.

I would really like to avoid having to deal with the Linux kernel AX25 stack.  I don't know Go, though.  I could learn it if you are interested.

The gensio library can do a lot of other things that might be useful, too.

Obviously it hasn't been around that long, but I'm planning to keep working on it.  I have my own uses for it.
