### ISSUE TITLE
transport: Add pactor support

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/wl2k-go#4]
Documentation and information regarding communicating with a pactor modem is needed.

Maybe bluetooth interface should be a priority?

**Comment by NAHANNIV** [comment]
Paclink-unix has this capability:
http://sourceforge.net/projects/paclink-unix/files/?source=navbar

Perhaps studying the code from that project could be of some use.

I would be very happy to help test when this is implemented.

**Comment by martinhpedersen** [comment]
Thank you!

Was was not aware of the similarity between an AX.25 TNC and Pactor interfaces, so I've justed assumed that paclink-unix's wl2kserial was for AX 25.

This will be very useful indeed.

Testing will be much appreciated when implementation is done. I'll keep you posted.

**Comment by NAHANNIV** [comment]
I'm not sure if it's applicable or not, but another Idea you might see in that project is providing an interface to a standard E-Mail client.

**Comment by akopac** [comment]
Ahhhhh but I think I discovered another way to do winlink2k without
paclink. BPQ.

Here is the downloads page for BPQ:
http://www.cantab.net/users/john.wiseman/Documents/Downloads.html

On there you can find the executables for windoze and Raspberry Pi.

Here are the instructions for installing on the Rpi:
http://www.cantab.net/users/john.wiseman/Documents/InstallingLINBPQ.htm

Note that there are differences for auto-starting on Debian Jesse vs.
Wheezy.

Here are more notes on the installation process, including links to
configuration file.
http://ag6qo.com/QOpilinbpqNotes.html

You can download this as a place to start if you like.
It's got more ports and capabilities than you'll need. More than likely
you'll need only two ports, the PACTOR one and the Telnet one (you'll need
telnet if you want to do control/configuration over your LAN). I've also
got an AXIP port, two 2m AX25 ports, and one 1.25m AX25 port.

You can also find more notes on the main configuration screens here:
http://ag6qo.com/BPQsysopGuide.html

You can use firebird or something else for a client 😀


-- 

*Andy Kopacwww.linkedin.com/in/andykopac
<http://www.linkedin.com/in/andykopac>*

**Comment by martinhpedersen** [comment]
@akopac:
Although I value your insight, this is an issue tracker for wl2k-go and not a general forum for discussing various winlink software. Please keep comments on topic and related to this project. Maybe you could re-post this on linux-hams or debian-hams.

@NAHANNIV:
Paclink(-unix) is a nice approach to interfacing between winlink and your favorite email client. I may write a client like that in the future, but for now I'll keep it simple and stick with the web ui. wl2k-go is organized a set of libraries that I hope developers some day will use to develop awesome cross-platform winlink software. But in the mean time, I'll continue working on `cmd/wl2k` (the command line/web ui client) and focus on a good and rich API for the libraries.

**Comment by martinhpedersen** [comment]
Back to topic:
Has anyone tested the wl2kserial.c from paclink-unix with an P4dragon DR-7800? Will it work?

**Comment by akopac** [comment]
Sorry Martin.  The comment came through nail and I didn't realize I was
replying through a forum.

On Tuesday, January 5, 2016, Martin Hebnes Pedersen <
notifications@github.com> wrote:

> @akopac <https://github.com/akopac>:
> Although I value your insight, this is an issue tracker for wl2k-go and
> not a general forum for discussing various winlink software. Please keep
> comments on topic and related to this project. Maybe you could re-post this
> on linux-hams or debian-hams.
>
> @NAHANNIV <https://github.com/NAHANNIV>:
> Paclink(-unix) is a nice approach to interfacing between winlink and your
> favorite email client. I may write a client like that in the future, but
> for now I'll keep it simple and stick with the web ui. wl2k-go is organized
> a set of libraries that I hope developers some day will use to develop
> awesome cross-platform winlink software. But in the mean time, I'll
> continue working on cmd/wl2k (the command line/web ui client) and focus
> on a good and rich API for the libraries.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/la5nta/wl2k-go/issues/4#issuecomment-168935094>.
>


-- 

*Andy Kopacwww.linkedin.com/in/andykopac
<http://www.linkedin.com/in/andykopac>*

**Comment by martinhpedersen** [comment]
No problem Andy :)

**Comment by martinhpedersen** [comment]
Quick update on this topic: linbpq may have GPL licensed code for communicating with a P4dragon on their "special baudrate".

**Comment by janhaag** [comment]
I'll cross-post part of what I wrote in several Posts on https://github.com/la5nta/pat/issues/40 in hope that it may help... 

First off, there's a lot of good information regarding Pactor controllers on the SCS website, http://www.scs-ptc.com/en/Downloads.html . According to their material all PTC models II and up have essentially the same set of commands (as far as I could tell they're identical over bluetooth and serial/USB connections), with the newest models having some extensions for Pactor 4 support. This would mean that SCS PTC II and up should be a reasonable initial target for Pactor support, with older models and the Timewave TNCs falling into the 'nice to have'-category, which would essentially require adding two new transports: Pactor 2 for narrowband operation and Pactor 3 (which automagically turns to Pactor 4 on a P4 in its default compatibility mode) for wideband operation. Older PTC models as well as the PK-232 and DSP-232 may be interesting targets at a later stage.

Anyway, I could well be missing something, so feel free to tear into what I just wrote.

**Comment by martinhpedersen** [comment]
See https://github.com/la5nta/pat/issues/40#issuecomment-366433776. I'm closing this issue since we are keeping the ptc driver in a separate repository for now.

Re-open when it's time to merge https://github.com/harenber/ptc-go with this project.
