### ISSUE TITLE
Support for KISS over TCP

### ISSUE THREAD

**Issue by dpkingston** [la5nta/wl2k-go#47]
It would be great if wl2k-go would support connecting to a TNC in KISS mode over TCP.  With LAN attached Raspberry Pi 3's running Direwolf, this is a great, sharable alternative to running the software on individual PCs wired to radios.

**Comment by martinhpedersen** [comment]
Hi!

Yes, that would be a great addition to wl2k-go. The only problem is that in order to support KISS directly, we need an AX.25 implementation to go with it. (Unless you're looking for some Go package that exposes the KISS frames?)

Ref issue #36.

**Comment by martinhpedersen** [comment]
Just realized that you maybe ment KISS over TCP support for Pat?

The same answer applies, but for a Linux only solution I believe this is possible by attaching a KISS device to the Linux kernel over TCP. I assume this has been done before for other AX.25 applications on Linux?

**Comment by kd8drx** [comment]
Seconding on this - it would be an excellent feature. Direwolf, especially, has some odd issues when providing a pseudo-serial devices for wl2k-go or other apps to use.

Another option would be supporting [AGW-over-TCP format](http://web.archive.org/web/20160501055912/http://uz7.ho.ua/includes/agwpeapi.htm), though that may be more work. However, Direwolf appears to have a full AX.25 stack built in that can be accessed using the AGW format, which I think would free you from needing to use Linux's built in stack. You would just send the necessary text commands to connect to a station and call the RMS - basically the same as the telnet mode.

If it's helpful, the Direwolf code is open source and the author is very responsive. The specific code (in C) for supporting KISS-over-TCP is [located here](https://github.com/wb2osz/direwolf/blob/master/kissnet.ct)

**Comment by martinhpedersen** [comment]
Yes - I agree that KISS (serial/tcp/udp) support and built-in AX.25 would be a very nice feature for Pat. But please note that KISS over tcp/udp is already possible if both ends of the tcp/udp connection is running Linux.

If Direwolf now implements a full AX.25 stack that are exposed over a TCP socket API, then we should add support for that. It would be a much more convenient solution than to port and maintain a full AX.25 stack internally in the project. Direwolf may be a great solution for macOS users looking for AX.25 packet capabilities. 

A PR is welcomed from anyone who have the time and know-how to start working on a AGW-over-TCP [transport](https://godoc.org/github.com/la5nta/wl2k-go/transport#pkg-subdirectories) package that would support Direwolf. :+1:  I will be happy to help and/or do it myself, but I don't have much time before autumn for such a task unfortunately.

**Comment by martinhpedersen** [comment]
See issue #56 regarding native support for KISS and AX.25.

I still welcome anyone who want to implement a net.Conn/net.Listener wrapper for the AGW interface that Direwolf exposes. That would be a nice way to support AX.25 on multiple platforms until #56 is resolved.

Closing this issue, since the main discussion is related to KISS and AX.25.
