### ISSUE TITLE
Add support for ICS forms

### ISSUE THREAD

**Issue by plughie** [la5nta/wl2k-go#58]
Winlink Express allows the operator to fill in the fields for standard ICS and ARRL message forms, then sending only the data of the form to reduce the message size. Pat could use this functionality to improve its utility for emergency communications, especially if the forms are compatible with Winlink Express.
- KM6DOV

**Comment by xylo04** [comment]
This is currently in progress in https://github.com/la5nta/pat/pull/206.

**Comment by martinhpedersen** [comment]
This was implemented in Pat and released with v0.11.0.
