### ISSUE TITLE
FBB: More lenient date\time parsing

### ISSUE THREAD

**Issue by xylo04** [la5nta/wl2k-go#76]
There's a bug report on the BPQ forum: https://groups.io/g/bpq32/message/35117. I don't know what the spec says about the date\time format, but BPQ evidently uses a different format than other RMS's.

```
MID: 7975_W7WXV
Date: 20220513002343 <<<< generated from BPQ web browser, blows up PAT clients
Type: Bulletin
From: W7WXV
To: kg7av
Subject: test 3
Mbo: W7WXV
Body: 56
File: 194 or-wxv-22-014.k2s
```

vs 

```
Date: 2022/05/13 00:27 <<<< generated from RMS Express, all clients handle this fine
```

**Comment by martinhpedersen** [comment]
Ah, yet another date format for the FBB Date header then 🤣 

The ["spec"](https://winlink.org/b2f) merely gives an example string of `1999/09/22 14:33`.

We already support [lots of formats](https://github.com/la5nta/wl2k-go/blob/b3b4be1c882d23e62024339b3706f6206d8a38cb/fbb/message.go#L66-L95), but let's add this one to the list of explicit winlink formats. 👍

**Comment by martinhpedersen** [comment]
Btw, should we verify that this is in UTC? 🤔

**Comment by martinhpedersen** [comment]
This is how Winlink describes the Date header:
> The Date: field is the UTC date and time the message was originated and is in the format YYYY/MM/DD HH:MM.
